rootProject.name = "foobar-webflux-service"
include(
        "foobar-core",
        "foobar-dataaccess",
        "foobar-user",
        "foobar-image",
        "foobar-sse",
        "foobar-websocket",
        "demo-concurrent",
        "demo-nio",
        "demo-aio",
        "demo-reactive-streams",
        "demo-reactive-streams-libraries",
        "demo-spring-webflux",
        "demo-spring-cloud-stream",
        "demo-spring-cloud-stream-kafka",
        "demo-spring-cloud-reactive-circuitbreaker",
        "demo-spring-cloud-reactive-circuit-breaker"
)
