spring:
  r2dbc:
    url: r2dbc:mysql://localhost:23306/example?useUnicode=true&serverTimezone=UTC
    username: user
    password: test1357
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html