version: '3.7'
services:
  example-mysql:
    image: mysql:5.7.39-debian
    restart: always
    #    command: --lower_case_table_names=1
    container_name: example-mysql
    hostname: example-mysql
    ports:
      - "23306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_USER_HOST=%
      - MYSQL_PASSWORD=test1357
      - MYSQL_DATABASE=coupon
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=test1357
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
    networks:
      - example-network
  example-redis:
    image: redis:7.0.2-alpine
    command: redis-server --port 6379
    #    container_name: redis-temp
    hostname: redis-normal
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    links:
      - example-redis-commander
    networks:
      - example-network
  example-redis-commander:
    image: rediscommander/redis-commander:latest
      # container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=redis-normal
    #      - REDIS_HOST=redis-normal:redis:16379
    ports:
      - 38081:8081
networks:
  example-network:
    external: true
#    driver: bridge