POST http://localhost:8080
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="ticker"
Content-Type: text/plain

SMCI
--WebAppBoundary--
###
